version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=130.162.60.179 #optional
    volumes:
      - /home/ubuntu/jellyfin//library:/config
      - /home/ubuntu/jellyfin/tvseries:/data/tvshows
      - /home/ubuntu/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
